### PR TITLE
replace membrane-element-file with membrane-file-plugin

### PR DESCRIPTION
**Pull request by AndrzejPodo**

### CODE REVIEW

**Review by mat-hek — CHANGES_REQUESTED** [review]
CI fails

**Comment by mickel8** [comment]
The error looks strange maybe try to run `mix deps.update --all --force` or restart pipeline. I have no problems locally

**Comment by mat-hek** [comment]
This may be caused by the old elixir in CI. Please try changing to `membrane/membrane:latest`

**Comment by AndrzejPodo** [comment]
@mat-hek  do you mean `- image: circleci/elixir:1.8` to `- image: circleci/elixir:latest` in `config.yml`?

**Comment by mickel8** [comment]
Try to use `- image: membrane/membrane:latest`

**Comment by AndrzejPodo** [comment]
Thanks 👍

**Review by mat-hek — APPROVED** [review]
CI fails

**Pull request merged**
